import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./icons.css";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-inter",
});

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon-dark.ico" media="(prefers-color-scheme: light)" />
            <link rel="icon" href="/favicon-light.ico" media="(prefers-color-scheme: dark)" />
        </head>
        <body className={inter.variable}>{children}</body>
        </html>
    );
}